
services:

  s3:
      build:
        context: datasources/
        dockerfile: Dockerfile
      container_name: s3_app
      ports:
        - "5001:5001"
      environment:
        - VALID_TOKEN=${VALID_TOKEN}
        - FILE_PATH=${FILE_PATH}
        - SECRET_KEY=${SECRET_KEY}
        - CSV_FILE_KEY=${CSV_FILE_KEY}
        - BUCKET_NAME=${BUCKET_NAME}
        - aws_access_key_id=${aws_access_key_id}
        - aws_secret_access_key=${aws_secret_access_key}

  machine-learning:
      build:
        context: machine-learging/
        dockerfile: Dockerfile
      container_name: machine_app
      ports:
        - "5002:5002"
      environment:
        - VALID_TOKEN=${VALID_TOKEN}
        - FILE_PATH=${FILE_PATH}
        - SECRET_KEY=${SECRET_KEY}
        - URL="http://s3:5001/resources-training"

volumes: {}